<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CnvRegulation.Application\CnvRegulation.Application.csproj" />
    <ProjectReference Include="..\CnvRegulation.Infrastructure\CnvRegulation.Infrastructure.csproj" />
    <ProjectReference Include="..\CnvRegulation.Domain\CnvRegulation.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="ModelContextProtocol" Version="1.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>cnv-regulation-mcpserver</UserSecretsId>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
