<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Schema\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CnvRegulation.Application\CnvRegulation.Application.csproj" />
    <ProjectReference Include="..\CnvRegulation.Domain\CnvRegulation.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
